// <auto-generated />
using System;
using Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WorkApp.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260124182014_InitialCreatess")]
    partial class InitialCreatess
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Account.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<int?>("JobTitleId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LineManager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Seniority")
                        .HasColumnType("int");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("JobTitleId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Domain.Enties.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4164),
                            DepartmentName = "Department 1",
                            Description = "Description for Department 1",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4167)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4363),
                            DepartmentName = "Department 2",
                            Description = "Description for Department 2",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4364)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4385),
                            DepartmentName = "Department 3",
                            Description = "Description for Department 3",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4386)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4402),
                            DepartmentName = "Department 4",
                            Description = "Description for Department 4",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4403)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4420),
                            DepartmentName = "Department 5",
                            Description = "Description for Department 5",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4420)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4440),
                            DepartmentName = "Department 6",
                            Description = "Description for Department 6",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4441)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4457),
                            DepartmentName = "Department 7",
                            Description = "Description for Department 7",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4457)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4474),
                            DepartmentName = "Department 8",
                            Description = "Description for Department 8",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4474)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4490),
                            DepartmentName = "Department 9",
                            Description = "Description for Department 9",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4490)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4523),
                            DepartmentName = "Department 10",
                            Description = "Description for Department 10",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(4523)
                        });
                });

            modelBuilder.Entity("Domain.Enties.JobTitle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Seniority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("JobTitles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6099),
                            DepartmentId = 1,
                            Description = "Description for Job Title 1",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 0,
                            Title = "Job Title 1",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6102)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6287),
                            DepartmentId = 2,
                            Description = "Description for Job Title 2",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 1,
                            Title = "Job Title 2",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6287)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6310),
                            DepartmentId = 3,
                            Description = "Description for Job Title 3",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 2,
                            Title = "Job Title 3",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6310)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6326),
                            DepartmentId = 4,
                            Description = "Description for Job Title 4",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 3,
                            Title = "Job Title 4",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6327)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6342),
                            DepartmentId = 5,
                            Description = "Description for Job Title 5",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 0,
                            Title = "Job Title 5",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6343)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6363),
                            DepartmentId = 6,
                            Description = "Description for Job Title 6",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 1,
                            Title = "Job Title 6",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6363)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6378),
                            DepartmentId = 7,
                            Description = "Description for Job Title 7",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 2,
                            Title = "Job Title 7",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6379)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6395),
                            DepartmentId = 8,
                            Description = "Description for Job Title 8",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 3,
                            Title = "Job Title 8",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6395)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6411),
                            DepartmentId = 9,
                            Description = "Description for Job Title 9",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 0,
                            Title = "Job Title 9",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6411)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6428),
                            DepartmentId = 10,
                            Description = "Description for Job Title 10",
                            IsActive = true,
                            IsDeleted = false,
                            Seniority = 1,
                            Title = "Job Title 10",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(6429)
                        });
                });

            modelBuilder.Entity("Domain.Enties.Leaves.LeaveAllocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveAllocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3570),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3573),
                            Username = "John"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3785),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 2,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3786),
                            Username = "Jane"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3804),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 3,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3805),
                            Username = "Mike"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3820),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3821),
                            Username = "Sarah"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3835),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 2,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3836),
                            Username = "David"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3865),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 3,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3866),
                            Username = "Emily"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3881),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3881),
                            Username = "Ryan"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3896),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 2,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3896),
                            Username = "Lisa"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3912),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 3,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3912),
                            Username = "Chris"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3928),
                            IsActive = true,
                            IsDeleted = false,
                            LeaveTypeId = 1,
                            NumberOfDays = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(3929),
                            Username = "Jessica"
                        });
                });

            modelBuilder.Entity("Domain.Enties.Leaves.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<DateTime>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfDays")
                        .HasColumnType("int");

                    b.Property<string>("RequestComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("LeaveTypeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("Domain.Enties.Leaves.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<int>("DefaultDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(7511),
                            DefaultDays = 10,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sick",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(7515)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(7518),
                            DefaultDays = 20,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Annual",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(7519)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(7521),
                            DefaultDays = 5,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Family",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(7521)
                        });
                });

            modelBuilder.Entity("Domain.Enties.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("TeamId");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(1866),
                            Description = "Description of Project 1",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 1",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 1,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(1869)
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2074),
                            Description = "Description of Project 2",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 2",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 2,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2074)
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2099),
                            Description = "Description of Project 3",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 3",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 3,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2100)
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2120),
                            Description = "Description of Project 4",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 4",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 4,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2120)
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 5,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2138),
                            Description = "Description of Project 5",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 5",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 5,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2139)
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 6,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2162),
                            Description = "Description of Project 6",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 6",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 6,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2163)
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 7,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2181),
                            Description = "Description of Project 7",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 7",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 7,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2181)
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 8,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2200),
                            Description = "Description of Project 8",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 8",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 8,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2200)
                        },
                        new
                        {
                            Id = 9,
                            ClientId = 9,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2218),
                            Description = "Description of Project 9",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 9",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 9,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2219)
                        },
                        new
                        {
                            Id = 10,
                            ClientId = 10,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2240),
                            Description = "Description of Project 10",
                            EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            IsActive = true,
                            IsDeleted = false,
                            ProjectName = "Project 10",
                            StartDate = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            TeamId = 10,
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 420, DateTimeKind.Local).AddTicks(2240)
                        });
                });

            modelBuilder.Entity("Domain.Enties.Shop.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExternalProductId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Domain.Enties.TimeSheets.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientName = "Eskom Holdings SOC Ltd",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 417, DateTimeKind.Local).AddTicks(4648),
                            Email = "info@EskomHoldingsSOCLtd.com",
                            Fax = "+27 11 123 4560",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4560",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 418, DateTimeKind.Local).AddTicks(4971)
                        },
                        new
                        {
                            Id = 2,
                            ClientName = "Sasol Limited",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2665),
                            Email = "info@SasolLimited.com",
                            Fax = "+27 11 123 4561",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4561",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2668)
                        },
                        new
                        {
                            Id = 3,
                            ClientName = "MTN Group Limited",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2795),
                            Email = "info@MTNGroupLimited.com",
                            Fax = "+27 11 123 4562",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4562",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2796)
                        },
                        new
                        {
                            Id = 4,
                            ClientName = "Naspers Limited",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2834),
                            Email = "info@NaspersLimited.com",
                            Fax = "+27 11 123 4563",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4563",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2835)
                        },
                        new
                        {
                            Id = 5,
                            ClientName = "Standard Bank Group Limited",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2854),
                            Email = "info@StandardBankGroupLimited.com",
                            Fax = "+27 11 123 4564",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4564",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2854)
                        },
                        new
                        {
                            Id = 6,
                            ClientName = "Shoprite Holdings Limited",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2881),
                            Email = "info@ShopriteHoldingsLimited.com",
                            Fax = "+27 11 123 4565",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4565",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2882)
                        },
                        new
                        {
                            Id = 7,
                            ClientName = "Absa Group Limited",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2899),
                            Email = "info@AbsaGroupLimited.com",
                            Fax = "+27 11 123 4566",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4566",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2900)
                        },
                        new
                        {
                            Id = 8,
                            ClientName = "Sibanye Stillwater Limited",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2917),
                            Email = "info@SibanyeStillwaterLimited.com",
                            Fax = "+27 11 123 4567",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4567",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2917)
                        },
                        new
                        {
                            Id = 9,
                            ClientName = "Anglo American Platinum Limited",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2934),
                            Email = "info@AngloAmericanPlatinumLimited.com",
                            Fax = "+27 11 123 4568",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4568",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2935)
                        },
                        new
                        {
                            Id = 10,
                            ClientName = "Vodacom Group Limited",
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2954),
                            Email = "info@VodacomGroupLimited.com",
                            Fax = "+27 11 123 4569",
                            IsActive = true,
                            IsDeleted = false,
                            Phone = "+27 11 123 4569",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(2955)
                        });
                });

            modelBuilder.Entity("Domain.Enties.TimeSheets.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectID")
                        .HasColumnType("int");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Domain.Enties.TimeSheets.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TeamLeader")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(8919),
                            Description = "Description for Team 1",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "John",
                            TeamName = "Team 1",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(8921)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9350),
                            Description = "Description for Team 2",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "Jane",
                            TeamName = "Team 2",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9351)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9374),
                            Description = "Description for Team 3",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "Mike",
                            TeamName = "Team 3",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9374)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9393),
                            Description = "Description for Team 4",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "Sarah",
                            TeamName = "Team 4",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9393)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9411),
                            Description = "Description for Team 5",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "David",
                            TeamName = "Team 5",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9411)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9445),
                            Description = "Description for Team 6",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "Emily",
                            TeamName = "Team 6",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9446)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9465),
                            Description = "Description for Team 7",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "Ryan",
                            TeamName = "Team 7",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9466)
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9484),
                            Description = "Description for Team 8",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "Lisa",
                            TeamName = "Team 8",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9484)
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9502),
                            Description = "Description for Team 9",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "Chris",
                            TeamName = "Team 9",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9502)
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9523),
                            Description = "Description for Team 10",
                            IsActive = true,
                            IsDeleted = false,
                            TeamLeader = "Jessica",
                            TeamName = "Team 10",
                            UpdatedAt = new DateTime(2026, 1, 24, 20, 20, 13, 419, DateTimeKind.Local).AddTicks(9524)
                        });
                });

            modelBuilder.Entity("Domain.Enties.TimeSheets.UserTeam", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeams");
                });

            modelBuilder.Entity("Domain.Entities.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Domain.Entities.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReceiverUserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenderUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Domain.Entities.TimeSheets.TimesheetEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimesheetDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("Date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TimesheetEntries");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<string>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", (string)null);
                });

            modelBuilder.Entity("Domain.Account.ApplicationUser", b =>
                {
                    b.HasOne("Domain.Enties.JobTitle", "JobTitle")
                        .WithMany("Users")
                        .HasForeignKey("JobTitleId");

                    b.Navigation("JobTitle");
                });

            modelBuilder.Entity("Domain.Enties.JobTitle", b =>
                {
                    b.HasOne("Domain.Enties.Department", "Department")
                        .WithMany("JobTitles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Domain.Enties.Leaves.LeaveAllocation", b =>
                {
                    b.HasOne("Domain.Enties.Leaves.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Domain.Enties.Leaves.LeaveRequest", b =>
                {
                    b.HasOne("Domain.Account.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Domain.Enties.Leaves.LeaveType", "LeaveType")
                        .WithMany()
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("LeaveType");
                });

            modelBuilder.Entity("Domain.Enties.Project", b =>
                {
                    b.HasOne("Domain.Enties.TimeSheets.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Enties.TimeSheets.Team", "Team")
                        .WithMany("Project")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Enties.TimeSheets.UserTeam", b =>
                {
                    b.HasOne("Domain.Enties.TimeSheets.Team", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Account.ApplicationUser", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.TimeSheets.TimesheetEntry", b =>
                {
                    b.HasOne("Domain.Enties.Project", "Project")
                        .WithMany("TimesheetEntries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Account.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Account.ApplicationUser", b =>
                {
                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("Domain.Enties.Department", b =>
                {
                    b.Navigation("JobTitles");
                });

            modelBuilder.Entity("Domain.Enties.JobTitle", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Enties.Project", b =>
                {
                    b.Navigation("TimesheetEntries");
                });

            modelBuilder.Entity("Domain.Enties.TimeSheets.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Domain.Enties.TimeSheets.Team", b =>
                {
                    b.Navigation("Project");

                    b.Navigation("UserTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
